django/source+code/Todos/Todos/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls'))
]

django/source+code/Todos/todo/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('add/',views.AddView.as_view()),
    path('about/',views.AboutView.as_view()),
    path('redirect/',views.RedirectAbout.as_view()),
    path('todo/<int:pk>/',views.DetailView.as_view(),name='todo'),
    path('update/<int:pk>/',views.UpdateTodoView.as_view(),name='up'),
    path('delete/<int:pk>/',views.DeleteTodoView.as_view(),name='delete')
]

django/source+code/Todos/todo/models.py
from django.db import models

# Create your models here.
class Todos(models.Model):
    todo = models.CharField(max_length=255)

django/source+code/Todos/todo/forms.py
from django import forms
from .models import Todos
class TodoForm(forms.ModelForm):
    class Meta:
        model = Todos
        fields = '__all__'
        widgets = {
                'todo':forms.TextInput(attrs={'class':'modelform-class'})
        }

django/source+code/Todos/todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from .forms import TodoForm
from .models import Todos
from django.views.generic.base import RedirectView,TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
# Create your views here.
def home(request):
    return render(request,'Hello World!')

# class HomeView(View):
#     def get(self,request):
#         #get request
#         todo = Todos.objects.all()
#         return render(request,"todo/index.html",{'todos':todo})

class HomeView(ListView):
    model = Todos
    ordering = ['-id']
    template_name = 'todo/index.html'
    context_object_name = 'todos'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['name'] = 'simar'
    #     return context

    # def get_queryset(self):
    #     return Todos.objects.filter(todo__icontains='s')

def details(request,id):
    todo = Todos.objects.get(id=id)
    return render(request,'todo/detail.html',{'todo':todo})

class DetailView(DetailView):
    model = Todos
    template_name = 'todo/detail.html'
    context_object_name = 'todo'

# class AddView(View):
#     def get(self,request):
#         form = TodoForm()
#         return render(request,'todo/add.html',{'form':form})
    
#     def post(self,request):
#         form = TodoForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/')
#         return render(request,'todo/add.html',{'form':form})

# class AddView(FormView):
#     template_name = 'todo/add.html'
#     form_class = TodoForm
#     success_url = '/'

#     def form_valid(self,form):
#         print(form.cleaned_data['todo'])
#         form.save()
        
#         return super().form_valid(form)

class AddView(CreateView):
    # model = Todos
    # fields = '__all__'
    form_class = TodoForm
    success_url = '/'
    template_name = 'todo/todos_add.html'
    # template_name_suffix = '_add'

class UpdateTodoView(UpdateView):
    model = Todos
    # fields= "__all__"
    form_class = TodoForm
    template_name = 'todo/todos_add.html'
    # template_name_suffix = '_add'
    success_url = '/'

class DeleteTodoView(DeleteView):
    model = Todos
    success_url = '/'


class AboutView(TemplateView):
    template_name = 'todo/about.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(kwargs)
        context['CompanyName'] = 'Taranjot Singh'
        return context
    
class RedirectAbout(RedirectView):
    pattern_name = 'home'
    query_string = True

django/source+code/Todos/todo/templates/todo/about.html
<h1>About page</h1>
<p>Company - {{CompanyName}}

django/source+code/Todos/todo/templates/todo/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add.html</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add">
    </form>
</body>
</html>

django/source+code/Todos/todo/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Todo</title>
</head>
<body>
    <h1>Detail.html Todo</h1>
    <h2>Todo Id = {{todo.id}} </h2>
    <h2>Todo = {{todo.todo}}</h2>
</body>
</html>

django/source+code/Todos/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Home</title>
    <style>
        .btn{
            padding: 5px 10px;
            background-color: red;
            border: 2px solid black;
            color: white;
            margin: 20px;
        }
    </style>
</head>
<body>
    <h1>Index.html</h1>
    <ul>
        {% comment %} {{todos_list}}
        {{object_list}} {% endcomment %}
        {% comment %} <div class='todos'>{{todos}}</div> {% endcomment %}
        
        {% comment %} <div class='todos_list'>{{todos_list}}</div> {% endcomment %}
        {% for todo in object_list  %}
        
            <a href='{% url "todo" todo.id %}' style="margin-top:20px">
        
                <li>{{todo.todo}}</li>
   
            </a>
       
            <br>
            <a class="btn" href="{% url 'up' todo.id %}">Update</a>
            <a href="{% url 'delete' todo.id %}"  class="btn">Delete</a>
        {% endfor %}
        {% comment %} {{name}} {% endcomment %}
    </ul>
</body>
</html>

django/source+code/Todos/todo/templates/todo/todos_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> <h1>Todos_form.html</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add">
    </form>
</body>
</html>

django/source+code/Todos/todo/templates/todo/todos_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.todo }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

django/source+code/Todos/todo/templates/todo/todos_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Todo</title>
</head>
<body>
    <h1>Detail Todo</h1>
    <h2>Todo Id = {{todos.id}} </h2>
    <h2>Todo = {{todos.todo}}</h2>
    {{object}}
</body>
</html>

django/source+code/Todos/todo/templates/todo/todos_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Home</title>
</head>
<body>
    <h1>Todos_list.html</h1>
    <ul>
        {% comment %} {{todos_list}}
        {{object_list}} {% endcomment %}
        {% for todo in object_list  %}
         <li>{{todo.todo}}</li>
        {% endfor %}
    </ul>
</body>
</html>